// authentication
export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
export const ACTION_UPDATE_AUTH = "ACTION_UPDATE_AUTH";
export const ACTION_REGISTER = "ACTION_REGISTER";

// app
export const ACTION_UPDATE_APP = "ACTION_UPDATE_APP";
export const ACTION_HANDLE_ERROR = "ACTION_HANDLE_ERROR";

// profile
export const ACTION_UPDATE_PROFILE = "ACTION_UPDATE_PROFILE";
